In [1]:
import pandas as pd
import duckdb
from IPython.display import display

In [2]:
path = (r"\Users\DELL\Downloads\archive")
aisles = pd.read_csv(r"\Users\DELL\Downloads\archive\aisles.csv")
departments = pd.read_csv(r"\Users\DELL\Downloads\archive\departments.csv")
order_products = pd.read_csv(r"\Users\DELL\Downloads\archive\order_products__prior.csv")
orders = pd.read_csv(r"\Users\DELL\Downloads\archive\orders.csv")
products = pd.read_csv(r"\Users\DELL\Downloads\archive\products.csv")

1. Calculate the total number of products associated with each department_id.

In [3]:

conn = duckdb.connect()
conn.sql("""
        SELECT department_id, count(*) FROM products
        GROUP BY  department_id; 
    """)

┌───────────────┬──────────────┐
│ department_id │ count_star() │
│     int64     │    int64     │
├───────────────┼──────────────┤
│             4 │         1684 │
│            19 │         6264 │
│            13 │         5371 │
│             7 │         4365 │
│             8 │          972 │
│            11 │         6563 │
│            16 │         3449 │
│            15 │         2092 │
│            18 │         1081 │
│             2 │          548 │
│            10 │           38 │
│            17 │         3085 │
│             9 │         1858 │
│            14 │         1115 │
│             5 │         1054 │
│            12 │          907 │
│             6 │         1139 │
│            20 │         1322 │
│             3 │         1516 │
│             1 │         4007 │
│            21 │         1258 │
└───────────────┴──────────────┘
  21 rows            2 columns

2. Find the average number of days that pass between a user's orders
(days_since_prior_order).

In [5]:
orders.dropna()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0
5,3367565,1,prior,6,2,7,19.0
...,...,...,...,...,...,...,...
3421078,2266710,206209,prior,10,5,18,29.0
3421079,1854736,206209,prior,11,4,10,30.0
3421080,626363,206209,prior,12,1,12,18.0
3421081,2977660,206209,prior,13,1,12,7.0
3421082,272231,206209,train,14,6,14,30.0

In [7]:
orders["days_since_prior_order"].mean()

np.float64(11.114836226863012)

3. Count how many orders were placed on each day of the week (order_dow)

In [14]:
conn.sql("""
        SELECT order_dow, count(*) from orders
       GROUP BY order_dow
       ORDER BY 1- 7
         """)

┌───────────┬──────────────┐
│ order_dow │ count_star() │
│   int64   │    int64     │
├───────────┼──────────────┤
│         0 │       600905 │
│         5 │       453368 │
│         2 │       467260 │
│         4 │       426339 │
│         1 │       587478 │
│         3 │       436972 │
│         6 │       448761 │
└───────────┴──────────────┘

4. Identify the single busiest hour of the day for shopping based on the total number of orders.

In [28]:
conn.sql("""
        SELECT order_hour_of_day,count(*)
        from orders
        GROUP BY order_hour_of_day
        LIMIT 1;
        """)

┌───────────────────┬──────────────┐
│ order_hour_of_day │ count_star() │
│       int64       │    int64     │
├───────────────────┼──────────────┤
│                 9 │       257812 │
└───────────────────┴──────────────┘

In [31]:
order_products

          order_id  product_id  add_to_cart_order  reordered
0                2       33120                  1          1
1                2       28985                  2          1
2                2        9327                  3          0
3                2       45918                  4          1
4                2       30035                  5          0
...            ...         ...                ...        ...
32434484   3421083       39678                  6          1
32434485   3421083       11352                  7          0
32434486   3421083        4600                  8          0
32434487   3421083       24852                  9          1
32434488   3421083        5020                 10          1

[32434489 rows x 4 columns]

5. Find the maximum value in the add_to_cart_order column to see the largest single
order cart size

In [33]:
conn.sql("""
        SELECT add_to_cart_order 
        from order_products
        group by add_to_cart_order
        LIMIT 1;
        """)

┌───────────────────┐
│ add_to_cart_order │
│       int64       │
├───────────────────┤
│                42 │
└───────────────────┘