In [1]:
import pandas as pd
import duckdb
from IPython.display import display

In [2]:
path = (r"\Users\DELL\Downloads\archive")
aisles = pd.read_csv(r"\Users\DELL\Downloads\archive\aisles.csv")
departments = pd.read_csv(r"\Users\DELL\Downloads\archive\departments.csv")
order_products = pd.read_csv(r"\Users\DELL\Downloads\archive\order_products__prior.csv")
orders = pd.read_csv(r"\Users\DELL\Downloads\archive\orders.csv")
products = pd.read_csv(r"\Users\DELL\Downloads\archive\products.csv")
departments

    department_id       department
0               1           frozen
1               2            other
2               3           bakery
3               4          produce
4               5          alcohol
5               6    international
6               7        beverages
7               8             pets
8               9  dry goods pasta
9              10             bulk
10             11    personal care
11             12     meat seafood
12             13           pantry
13             14        breakfast
14             15     canned goods
15             16       dairy eggs
16             17        household
17             18           babies
18             19           snacks
19             20             deli
20             21          missing

1. Create a list of product names alongside their respective department names.

In [3]:
conn = duckdb.connect()
conn.sql(
    """
    SELECT p.product_name,d.department
    from products p
    LEFT JOIN departments d
    ON p.department_id = d.department_id
    """)

┌───────────────────────────────────────────────────────────────────┬─────────────────┐
│                           product_name                            │   department    │
│                              varchar                              │     varchar     │
├───────────────────────────────────────────────────────────────────┼─────────────────┤
│ Chocolate Sandwich Cookies                                        │ snacks          │
│ All-Seasons Salt                                                  │ pantry          │
│ Robust Golden Unsweetened Oolong Tea                              │ beverages       │
│ Smart Ones Classic Favorites Mini Rigatoni With Vodka Cream Sauce │ frozen          │
│ Green Chile Anytime Sauce                                         │ pantry          │
│ Dry Nose Oil                                                      │ personal care   │
│ Pure Coconut Water With Orange                                    │ beverages       │
│ Cut Russet Potatoes Steam N' Mash                                 │ frozen          │
│ Light Strawberry Blueberry Yogurt                                 │ dairy eggs      │
│ Sparkling Orange Juice & Prickly Pear Beverage                    │ beverages       │
│              ·                                                    │     ·           │
│              ·                                                    │     ·           │
│              ·                                                    │     ·           │
│ Stir Fry Sauce Broccoli Beef                                      │ international   │
│ Touch Y-Peeler                                                    │ household       │
│ Organic French Green Lentils                                      │ dry goods pasta │
│ Light Churned Vanilla Bean                                        │ frozen          │
│ Sesame Seed New York Style Bagels                                 │ bakery          │
│ Less Sodium Soy Sauce                                             │ international   │
│ Italian Style Vegetables                                          │ frozen          │
│ Ice Cream, Natural, Vanilla Bean                                  │ frozen          │
│ Cheese, Spreadable, Crescenza-Stracchino                          │ dairy eggs      │
│ Refresher Strawberry Lemonade                                     │ beverages       │
└───────────────────────────────────────────────────────────────────┴─────────────────┘
  ? rows (>9999 rows, 20 shown)                                             2 columns

2. Retrieve a list showing order_id and the names of the products contained in each order

In [4]:
order_products

          order_id  product_id  add_to_cart_order  reordered
0                2       33120                  1          1
1                2       28985                  2          1
2                2        9327                  3          0
3                2       45918                  4          1
4                2       30035                  5          0
...            ...         ...                ...        ...
32434484   3421083       39678                  6          1
32434485   3421083       11352                  7          0
32434486   3421083        4600                  8          0
32434487   3421083       24852                  9          1
32434488   3421083        5020                 10          1

[32434489 rows x 4 columns]

In [5]:
conn.sql(
    """
    SELECT o.order_id, p.product_name
    from order_products o
    LEFT JOIN products p
    ON o.product_id = p.product_id
   
    """)

┌──────────┬───────────────────────────────────────────────────────────────────────────────────┐
│ order_id │                                   product_name                                    │
│  int64   │                                      varchar                                      │
├──────────┼───────────────────────────────────────────────────────────────────────────────────┤
│    10826 │ Apple Lemon Cayenne Ginger                                                        │
│    10826 │ Organic Turmeric Tonic Juice                                                      │
│    10826 │ Arugula, Kale, Apple, Romaine, Celery, Cucumber, Lemon, Ginger Cold Pressed Juice │
│    10826 │ Carrot Golden Beet Juice                                                          │
│    10826 │ Organic Grade A Free Range Large Brown Eggs                                       │
│    10826 │ Organic Chicken Noodle Soup                                                       │
│    10826 │ All Natural Cinnamon Raisin Bread                                                 │
│    10826 │ Bag of Organic Bananas                                                            │
│    10826 │ Organic Cane Sugar                                                                │
│    10827 │ Gluten Free Dark Chocolate Chunk Chewy with a Crunch Granola Bars                 │
│      ·   │                       ·                                                           │
│      ·   │                       ·                                                           │
│      ·   │                       ·                                                           │
│    32611 │ Natural Black Cherry Gels Gelatin Free Snacks                                     │
│    32611 │ Turbana Sweet Plantain Chips                                                      │
│    32612 │ French Vanilla Ice Cream                                                          │
│    32612 │ Vitamin D Milk                                                                    │
│    32612 │ Organic Half & Half                                                               │
│    32613 │ Rice Krispies Treats Original Crispy Marshmallow Squares                          │
│    32613 │ Family Size Peanut Butter Cracker Sandwiches                                      │
│    32613 │ Lunchables Pepperoni Pizza                                                        │
│    32613 │ Lunchable Extra Cheesy Pizza                                                      │
│    32614 │ Organic Ketchup                                                                   │
└──────────┴───────────────────────────────────────────────────────────────────────────────────┘
  ? rows (>9999 rows, 20 shown)                                                      2 columns

3. List all products and the name of the aisle they belong to.

In [6]:
aisles

     aisle_id                       aisle
0           1       prepared soups salads
1           2           specialty cheeses
2           3         energy granola bars
3           4               instant foods
4           5  marinades meat preparation
..        ...                         ...
129       130    hot cereal pancake mixes
130       131                   dry pasta
131       132                      beauty
132       133  muscles joints pain relief
133       134  specialty wines champagnes

[134 rows x 2 columns]

In [7]:
conn.sql("""
    SELECT 
    p.product_name,
    a.aisle
    FROM products p
    LEFT JOIN aisles a
    ON p.aisle_id = a.aisle_id;
    """)

┌───────────────────────────────────────────────────────────────────┬───────────────────────────────┐
│                           product_name                            │             aisle             │
│                              varchar                              │            varchar            │
├───────────────────────────────────────────────────────────────────┼───────────────────────────────┤
│ Chocolate Sandwich Cookies                                        │ cookies cakes                 │
│ All-Seasons Salt                                                  │ spices seasonings             │
│ Robust Golden Unsweetened Oolong Tea                              │ tea                           │
│ Smart Ones Classic Favorites Mini Rigatoni With Vodka Cream Sauce │ frozen meals                  │
│ Green Chile Anytime Sauce                                         │ marinades meat preparation    │
│ Dry Nose Oil                                                      │ cold flu allergy              │
│ Pure Coconut Water With Orange                                    │ juice nectars                 │
│ Cut Russet Potatoes Steam N' Mash                                 │ frozen produce                │
│ Light Strawberry Blueberry Yogurt                                 │ yogurt                        │
│ Sparkling Orange Juice & Prickly Pear Beverage                    │ water seltzer sparkling water │
│              ·                                                    │      ·                        │
│              ·                                                    │      ·                        │
│              ·                                                    │      ·                        │
│ Stir Fry Sauce Broccoli Beef                                      │ asian foods                   │
│ Touch Y-Peeler                                                    │ kitchen supplies              │
│ Organic French Green Lentils                                      │ grains rice dried goods       │
│ Light Churned Vanilla Bean                                        │ ice cream ice                 │
│ Sesame Seed New York Style Bagels                                 │ breakfast bakery              │
│ Less Sodium Soy Sauce                                             │ asian foods                   │
│ Italian Style Vegetables                                          │ frozen produce                │
│ Ice Cream, Natural, Vanilla Bean                                  │ ice cream ice                 │
│ Cheese, Spreadable, Crescenza-Stracchino                          │ specialty cheeses             │
│ Refresher Strawberry Lemonade                                     │ energy sports drinks          │
└───────────────────────────────────────────────────────────────────┴───────────────────────────────┘
  ? rows (>9999 rows, 20 shown)                                                           2 columns

4. Calculate the total number of items sold per department name.

In [11]:
conn.sql("""
    SELECT 
    d.department,
    COUNT(*) AS total_items_sold
FROM order_products op
JOIN products p
    ON op.product_id = p.product_id
JOIN departments d
    ON p.department_id = d.department_id
GROUP BY d.department
ORDER BY total_items_sold DESC;
""")

┌─────────────────┬──────────────────┐
│   department    │ total_items_sold │
│     varchar     │      int64       │
├─────────────────┼──────────────────┤
│ produce         │          9479291 │
│ dairy eggs      │          5414016 │
│ snacks          │          2887550 │
│ beverages       │          2690129 │
│ frozen          │          2236432 │
│ pantry          │          1875577 │
│ bakery          │          1176787 │
│ canned goods    │          1068058 │
│ deli            │          1051249 │
│ dry goods pasta │           866627 │
│ household       │           738666 │
│ breakfast       │           709569 │
│ meat seafood    │           708931 │
│ personal care   │           447123 │
│ babies          │           423802 │
│ international   │           269253 │
│ alcohol         │           153696 │
│ pets            │            97724 │
│ missing         │            69145 │
│ other           │            36291 │
│ bulk            │            34573 │
└─────────────────┴──────────────────┘
  21 rows                  2 columns

5. Display user_id, order_id, and product_name for the first 20 records in the dataset.

In [14]:
conn.sql(
    """
    SELECT o.user_id,op.order_id,p.product_name
    FROM order_products op
    JOIN orders o
    ON op.order_id = o.order_id
    JOIN products p
    ON op.product_id = p.product_id
    LIMIT 20;
    """
)

┌─────────┬──────────┬───────────────────────────────────────────────────────┐
│ user_id │ order_id │                     product_name                      │
│  int64  │  int64   │                        varchar                        │
├─────────┼──────────┼───────────────────────────────────────────────────────┤
│  202279 │        2 │ Organic Egg Whites                                    │
│  202279 │        2 │ Michigan Organic Kale                                 │
│  202279 │        2 │ Garlic Powder                                         │
│  202279 │        2 │ Coconut Butter                                        │
│  202279 │        2 │ Natural Sweetener                                     │
│  202279 │        2 │ Carrots                                               │
│  202279 │        2 │ Original Unflavored Gelatine Mix                      │
│  202279 │        2 │ All Natural No Stir Creamy Almond Butter              │
│  202279 │        2 │ Classic Blend Cole Slaw                               │
│  205970 │        3 │ Total 2% with Strawberry Lowfat Greek Strained Yogurt │
│  205970 │        3 │ Unsweetened Almondmilk                                │
│  205970 │        3 │ Lemons                                                │
│  205970 │        3 │ Organic Baby Spinach                                  │
│  205970 │        3 │ Unsweetened Chocolate Almond Breeze Almond Milk       │
│  205970 │        3 │ Organic Ginger Root                                   │
│  205970 │        3 │ Air Chilled Organic Boneless Skinless Chicken Breasts │
│  205970 │        3 │ Organic Ezekiel 49 Bread Cinnamon Raisin              │
│  178520 │        4 │ Plain Pre-Sliced Bagels                               │
│  178520 │        4 │ Honey/Lemon Cough Drops                               │
│  178520 │        4 │ Chewy 25% Low Sugar Chocolate Chip Granola            │
└─────────┴──────────┴───────────────────────────────────────────────────────┘
  20 rows                                                          3 columns